language: go
go: 
  - 1.11.x

services:
  - docker

install:
  - go get mvdan.cc/sh/cmd/shfmt

script: 
  - docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:stable example-script.sh
  - shfmt -ci -i 2 -d example-script.sh
  - docker run --rm -i -v $PWD:/lint/input:ro zemanlx/remark-lint --frail .